// Data based on ICAO-compliant sources for standard adult passports.
// Where multiple options are available (e.g., 5 or 10 years), the maximum is used.
const validityData: Record<string, number> = {
    'AFG': 5,
    'ALB': 10,
    'DZA': 10,
    'AND': 10,
    'AGO': 5,
    'ATG': 10,
    'ARG': 10,
    'ARM': 10,
    'AUS': 10,
    'AUT': 10,
    'AZE': 10,
    'BHS': 10,
    'BHR': 5,
    'BGD': 10,
    'BRB': 10,
    'BLR': 10,
    'BEL': 7,
    'BLZ': 10,
    'BOL': 6,
    'BIH': 10,
    'BWA': 10,
    'BRA': 10,
    'BRN': 5,
    'BGR': 10,
    'KHM': 10,
    'CAN': 10,
    'CHL': 10,
    'CHN': 10,
    'COL': 10,
    'HRV': 10,
    'CUB': 6,
    'CYP': 10,
    'CZE': 10,
    'DNK': 10,
    'EST': 10,
    'FIN': 5,
    'FRA': 10,
    'GEO': 10,
    'DEU': 10, // 10 years for adults >= 24
    'GRC': 10,
    'HUN': 10,
    'ISL': 10,
    'IND': 10,
    'IDN': 10,
    'IRN': 5,
    'IRL': 10,
    'ITA': 10,
    'JPN': 10,
    'KAZ': 10,
    'KEN': 10,
    'KWT': 10,
    'LAO': 10,
    'LVA': 10,
    'LTU': 10,
    'LUX': 5,
    'MLT': 10,
    'MEX': 10,
    'MNG': 10,
    'MNE': 10,
    'MAR': 5,
    'NLD': 10,
    'NZL': 10,
    'NGA': 5,
    'NOR': 10,
    'PAK': 10,
    'PER': 10,
    'PHL': 10,
    'POL': 10,
    'PRT': 5,
    'ROU': 10,
    'RUS': 10,
    'SAU': 10,
    'SRB': 10,
    'SGP': 10,
    'SVK': 10,
    'SVN': 10,
    'ZAF': 10,
    'KOR': 10,
    'ESP': 10,
    'LKA': 10,
    'SWE': 5,
    'CHE': 10,
    'THA': 10,
    'TUR': 10,
    'UGA': 10,
    'ARE': 5,
    'GBR': 10,
    'USA': 10,
    'VEN': 10,
    'VNM': 10,
    'YEM': 6,
    'ZMB': 10,
    'ZWE': 10,
};

/**
 * Gets the maximum passport validity in years for a given country.
 * @param countryCode The 3-letter ISO 3166-1 alpha-3 country code.
 * @returns The validity period in years, or undefined if not found.
 */
export const getPassportValidity = (countryCode: string): number | undefined => {
    return validityData[countryCode];
};
