
import { IdData, DocumentType, Gender } from '../types';
import { COUNTRIES } from '../constants';
import { getPassportValidity } from './passportValidity';

// Helper to get a random element from an array
const getRandom = <T>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)];

// Sample names for more realistic data
const FIRST_NAMES = ['JAMES', 'MARY', 'JOHN', 'PATRICIA', 'ROBERT', 'JENNIFER', 'MICHAEL', 'LINDA', 'WILLIAM', 'ELIZABETH', 'DAVID', 'BARBARA', 'RICHARD', 'SUSAN', 'JOSEPH', 'JESSICA', 'THOMAS', 'SARAH', 'CHARLES', 'KAREN'];
const LAST_NAMES = ['SMITH', 'JOHNSON', 'WILLIAMS', 'BROWN', 'JONES', 'GARCIA', 'MILLER', 'DAVIS', 'RODRIGUEZ', 'MARTINEZ', 'HERNANDEZ', 'LOPEZ', 'GONZALEZ', 'WILSON', 'ANDERSON', 'THOMAS', 'TAYLOR', 'MOORE', 'JACKSON', 'MARTIN'];

// Generates a random date between two dates
const randomDate = (start: Date, end: Date): Date => {
    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
};

// Formats a Date object to 'YYYY-MM-DD'
const formatDate = (date: Date): string => date.toISOString().split('T')[0];

// Generates a random alphanumeric string
const randomAlphanumeric = (length: number): string => {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let result = '';
    for (let i = 0; i < length; i++) {
        result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
};

export const generateRandomIdData = (): IdData => {
    const documentType = getRandom([DocumentType.PASSPORT, DocumentType.ID_CARD]);
    const country = getRandom(COUNTRIES);
    const gender = getRandom([Gender.MALE, Gender.FEMALE, Gender.OTHER]);
    
    const dateOfBirthDate = randomDate(new Date(1950, 0, 1), new Date(2005, 11, 31));
    const dateOfBirth = formatDate(dateOfBirthDate);

    // Issue date must be after 18th birthday and before today
    const minIssueDate = new Date(dateOfBirthDate);
    minIssueDate.setFullYear(minIssueDate.getFullYear() + 18);
    const dateOfIssueDate = randomDate(minIssueDate, new Date());
    const dateOfIssue = formatDate(dateOfIssueDate);
    
    // Calculate expiry date based on issue date and country rules
    let expiryDate = '';
    if (documentType === DocumentType.PASSPORT) {
        const validityYears = getPassportValidity(country.value) || 10;
        const expiryDateDate = new Date(dateOfIssueDate);
        expiryDateDate.setFullYear(expiryDateDate.getFullYear() + validityYears);
        expiryDate = formatDate(expiryDateDate);
    } else { // ID Cards often have different rules, let's just do 10 years for simplicity
        const expiryDateDate = new Date(dateOfIssueDate);
        expiryDateDate.setFullYear(expiryDateDate.getFullYear() + 10);
        expiryDate = formatDate(expiryDateDate);
    }

    const data: IdData = {
        documentType,
        issuingCountry: country.value,
        documentNumber: randomAlphanumeric(9),
        firstName: getRandom(FIRST_NAMES),
        lastName: getRandom(LAST_NAMES),
        nationality: country.value,
        dateOfBirth,
        gender,
        dateOfIssue,
        expiryDate,
        personalNumber: '', // Will be generated by the effect in App.tsx
        includePersonalNumberInMrz: Math.random() > 0.5,
    };

    return data;
};